object Versions {
    const val kotlin = "1.6.10"
    const val buildGradle = "7.2.1"
    const val appCompat = "1.3.0"
    const val coreKtx = "1.7.0"
    const val material = "1.7.0"
    const val constraintLayout = "2.1.4"
    const val legacy = "1.0.0"
    const val daggerHilt = "2.40.5"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigation = "1.0.0"
    const val fragmentNav = "2.5.3"
    const val room = "2.4.3"
    const val livedata = "2.5.1"
    const val liveEvent = "1.2.0"
    const val coroutines = "1.6.4"
    const val lifecycle = "2.6.0-alpha03"
    const val glide = "4.11.0"
    const val jupiter = "5.9.0"
    const val junit = "4.13.2"
    const val timber = "5.0.1"
    const val core = "2.1.0"
    const val testRunner = "1.4.0"
    const val junit5 = "1.3.0"
    const val truth = "1.0.1"
    const val junitExt = "1.1.3"
    const val espresso = "3.4.0"
    const val retrofit = "2.9.0"
    const val canary = "2.8.0"
    const val retrofitAdapter = "0.9.2"
    const val chucker = "3.5.2"

}